# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.5
yarn_mappings=1.21.5+build.1
loader_version=0.16.14
loom_version=1.10-SNAPSHOT
sodium_version=mc1.21.5-0.6.11-fabric
lithium_version=mc1.21.5-0.16.0-fabric
iris_version=1.8.5+1.21.4-fabric

# Mod Properties
mod_version=1.0.0
maven_group=com.charmonium
archives_base_name=charmonium

# Dependencies
fabric_version=0.126.0+1.21.5